// Hearth wire protocol — v1
//
// All RPCs run over a single gRPC service. Worker, client, and admin calls
// are mixed deliberately: every Hearth deployment runs exactly one
// coordinator listening for all of them, and splitting services would only
// add deployment complexity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hearth/v1/hearth.proto

package hearthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_STATE_UNSPECIFIED State = 0
	State_STATE_QUEUED      State = 1
	State_STATE_LEASED      State = 2
	State_STATE_SUCCEEDED   State = 3
	State_STATE_FAILED      State = 4
	State_STATE_CANCELLED   State = 5
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_QUEUED",
		2: "STATE_LEASED",
		3: "STATE_SUCCEEDED",
		4: "STATE_FAILED",
		5: "STATE_CANCELLED",
	}
	State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_QUEUED":      1,
		"STATE_LEASED":      2,
		"STATE_SUCCEEDED":   3,
		"STATE_FAILED":      4,
		"STATE_CANCELLED":   5,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_hearth_v1_hearth_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_hearth_v1_hearth_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{0}
}

type BlobRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{0}
}

func (x *BlobRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BlobRef) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BackoffPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initial       *durationpb.Duration   `protobuf:"bytes,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Max           *durationpb.Duration   `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	Jitter        float64                `protobuf:"fixed64,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackoffPolicy) Reset() {
	*x = BackoffPolicy{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackoffPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackoffPolicy) ProtoMessage() {}

func (x *BackoffPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackoffPolicy.ProtoReflect.Descriptor instead.
func (*BackoffPolicy) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{1}
}

func (x *BackoffPolicy) GetInitial() *durationpb.Duration {
	if x != nil {
		return x.Initial
	}
	return nil
}

func (x *BackoffPolicy) GetMax() *durationpb.Duration {
	if x != nil {
		return x.Max
	}
	return nil
}

func (x *BackoffPolicy) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *BackoffPolicy) GetJitter() float64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

type Spec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Blobs         []*BlobRef             `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,4,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	LeaseTtl      *durationpb.Duration   `protobuf:"bytes,5,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	Backoff       *BackoffPolicy         `protobuf:"bytes,6,opt,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spec) Reset() {
	*x = Spec{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spec) ProtoMessage() {}

func (x *Spec) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spec.ProtoReflect.Descriptor instead.
func (*Spec) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{2}
}

func (x *Spec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Spec) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Spec) GetBlobs() []*BlobRef {
	if x != nil {
		return x.Blobs
	}
	return nil
}

func (x *Spec) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Spec) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

func (x *Spec) GetBackoff() *BackoffPolicy {
	if x != nil {
		return x.Backoff
	}
	return nil
}

type Lease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeasedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=leased_at,json=leasedAt,proto3" json:"leased_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{3}
}

func (x *Lease) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Lease) GetLeasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeasedAt
	}
	return nil
}

func (x *Lease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Blobs         []*BlobRef             `protobuf:"bytes,2,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{4}
}

func (x *Result) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Result) GetBlobs() []*BlobRef {
	if x != nil {
		return x.Blobs
	}
	return nil
}

type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// percent is in [0, 1].
	Percent float64 `protobuf:"fixed64,1,opt,name=percent,proto3" json:"percent,omitempty"`
	// message is a free-form human-readable description.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// reported_at is the worker-side wall-clock time of the report.
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{5}
}

func (x *Progress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Progress) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *Spec                  `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	State         State                  `protobuf:"varint,3,opt,name=state,proto3,enum=hearth.v1.State" json:"state,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Lease         *Lease                 `protobuf:"bytes,5,opt,name=lease,proto3" json:"lease,omitempty"`
	Result        *Result                `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Progress      *Progress              `protobuf:"bytes,11,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Job) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STATE_UNSPECIFIED
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Job) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Kinds         []string               `protobuf:"bytes,5,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *WorkerInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *WorkerInfo) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *WorkerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WorkerInfo) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *WorkerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *Spec                  `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitJobRequest) GetSpec() *Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []State                `protobuf:"varint,1,rep,packed,name=states,proto3,enum=hearth.v1.State" json:"states,omitempty"`
	Kinds         []string               `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{11}
}

func (x *ListJobsRequest) GetStates() []State {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListJobsRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{13}
}

func (x *CancelJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{14}
}

type WatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchJobRequest) Reset() {
	*x = WatchJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchJobRequest) ProtoMessage() {}

func (x *WatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchJobRequest.ProtoReflect.Descriptor instead.
func (*WatchJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{15}
}

func (x *WatchJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *WorkerInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterWorkerRequest) GetInfo() *WorkerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type RegisterWorkerResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterWorkerResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

type LeaseJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Kinds         []string               `protobuf:"bytes,2,rep,name=kinds,proto3" json:"kinds,omitempty"`
	PollTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=poll_timeout,json=pollTimeout,proto3" json:"poll_timeout,omitempty"`
	LeaseTtl      *durationpb.Duration   `protobuf:"bytes,4,opt,name=lease_ttl,json=leaseTtl,proto3" json:"lease_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseJobRequest) Reset() {
	*x = LeaseJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseJobRequest) ProtoMessage() {}

func (x *LeaseJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseJobRequest.ProtoReflect.Descriptor instead.
func (*LeaseJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{18}
}

func (x *LeaseJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LeaseJobRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *LeaseJobRequest) GetPollTimeout() *durationpb.Duration {
	if x != nil {
		return x.PollTimeout
	}
	return nil
}

func (x *LeaseJobRequest) GetLeaseTtl() *durationpb.Duration {
	if x != nil {
		return x.LeaseTtl
	}
	return nil
}

type LeaseJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty job means "no work, try again". This keeps the wire shape simple.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseJobResponse) Reset() {
	*x = LeaseJobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseJobResponse) ProtoMessage() {}

func (x *LeaseJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseJobResponse.ProtoReflect.Descriptor instead.
func (*LeaseJobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{19}
}

func (x *LeaseJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type HeartbeatRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// progress is optional; the worker piggy-backs progress reports on
	// heartbeat to avoid a separate RPC.
	Progress      *Progress `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type HeartbeatResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// If true, the coordinator wants the worker to abandon the job (ctx cancel).
	Cancel        bool `protobuf:"varint,2,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *HeartbeatResponse) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

type CompleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobRequest) Reset() {
	*x = CompleteJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobRequest) ProtoMessage() {}

func (x *CompleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobRequest.ProtoReflect.Descriptor instead.
func (*CompleteJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{22}
}

func (x *CompleteJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteJobRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type CompleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobResponse) Reset() {
	*x = CompleteJobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobResponse) ProtoMessage() {}

func (x *CompleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobResponse.ProtoReflect.Descriptor instead.
func (*CompleteJobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{23}
}

type FailJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailJobRequest) Reset() {
	*x = FailJobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailJobRequest) ProtoMessage() {}

func (x *FailJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailJobRequest.ProtoReflect.Descriptor instead.
func (*FailJobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{24}
}

func (x *FailJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailJobRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FailJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WillRetry     bool                   `protobuf:"varint,1,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailJobResponse) Reset() {
	*x = FailJobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailJobResponse) ProtoMessage() {}

func (x *FailJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailJobResponse.ProtoReflect.Descriptor instead.
func (*FailJobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{25}
}

func (x *FailJobResponse) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

func (x *FailJobResponse) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

type PutBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PutBlobRequest_Header
	//	*PutBlobRequest_Chunk
	Payload       isPutBlobRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{26}
}

func (x *PutBlobRequest) GetPayload() isPutBlobRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PutBlobRequest) GetHeader() *PutBlobHeader {
	if x != nil {
		if x, ok := x.Payload.(*PutBlobRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PutBlobRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PutBlobRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPutBlobRequest_Payload interface {
	isPutBlobRequest_Payload()
}

type PutBlobRequest_Header struct {
	Header *PutBlobHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PutBlobRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PutBlobRequest_Header) isPutBlobRequest_Payload() {}

func (*PutBlobRequest_Chunk) isPutBlobRequest_Payload() {}

type PutBlobHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: hint for the total expected size (bytes).
	Size          int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobHeader) Reset() {
	*x = PutBlobHeader{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobHeader) ProtoMessage() {}

func (x *PutBlobHeader) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobHeader.ProtoReflect.Descriptor instead.
func (*PutBlobHeader) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{27}
}

func (x *PutBlobHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PutBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobResponse) Reset() {
	*x = PutBlobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobResponse) ProtoMessage() {}

func (x *PutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobResponse.ProtoReflect.Descriptor instead.
func (*PutBlobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{28}
}

func (x *PutBlobResponse) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{29}
}

func (x *GetBlobRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{30}
}

func (x *GetBlobResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type HasBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasBlobRequest) Reset() {
	*x = HasBlobRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasBlobRequest) ProtoMessage() {}

func (x *HasBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasBlobRequest.ProtoReflect.Descriptor instead.
func (*HasBlobRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{31}
}

func (x *HasBlobRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type HasBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Present       bool                   `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasBlobResponse) Reset() {
	*x = HasBlobResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasBlobResponse) ProtoMessage() {}

func (x *HasBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasBlobResponse.ProtoReflect.Descriptor instead.
func (*HasBlobResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{32}
}

func (x *HasBlobResponse) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{33}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*WorkerInfo          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_hearth_v1_hearth_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hearth_v1_hearth_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_hearth_v1_hearth_proto_rawDescGZIP(), []int{34}
}

func (x *ListNodesResponse) GetNodes() []*WorkerInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_hearth_v1_hearth_proto protoreflect.FileDescriptor

const file_hearth_v1_hearth_proto_rawDesc = "" +
	"\n" +
	"\x16hearth/v1/hearth.proto\x12\thearth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"5\n" +
	"\aBlobRef\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xa9\x01\n" +
	"\rBackoffPolicy\x123\n" +
	"\ainitial\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\ainitial\x12+\n" +
	"\x03max\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03max\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\x12\x16\n" +
	"\x06jitter\x18\x04 \x01(\x01R\x06jitter\"\xed\x01\n" +
	"\x04Spec\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12(\n" +
	"\x05blobs\x18\x03 \x03(\v2\x12.hearth.v1.BlobRefR\x05blobs\x12!\n" +
	"\fmax_attempts\x18\x04 \x01(\x05R\vmaxAttempts\x126\n" +
	"\tlease_ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\x122\n" +
	"\abackoff\x18\x06 \x01(\v2\x18.hearth.v1.BackoffPolicyR\abackoff\"\x98\x01\n" +
	"\x05Lease\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x127\n" +
	"\tleased_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bleasedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\x06Result\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12(\n" +
	"\x05blobs\x18\x02 \x03(\v2\x12.hearth.v1.BlobRefR\x05blobs\"{\n" +
	"\bProgress\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x01R\apercent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\vreported_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\"\xd1\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04spec\x18\x02 \x01(\v2\x0f.hearth.v1.SpecR\x04spec\x12&\n" +
	"\x05state\x18\x03 \x01(\x0e2\x10.hearth.v1.StateR\x05state\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12&\n" +
	"\x05lease\x18\x05 \x01(\v2\x10.hearth.v1.LeaseR\x05lease\x12)\n" +
	"\x06result\x18\x06 \x01(\v2\x11.hearth.v1.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\x12:\n" +
	"\vnext_run_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\bprogress\x18\v \x01(\v2\x13.hearth.v1.ProgressR\bprogress\"\xfe\x01\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x14\n" +
	"\x05kinds\x18\x05 \x03(\tR\x05kinds\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x127\n" +
	"\tjoined_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"7\n" +
	"\x10SubmitJobRequest\x12#\n" +
	"\x04spec\x18\x01 \x01(\v2\x0f.hearth.v1.SpecR\x04spec\"#\n" +
	"\x11SubmitJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x0fListJobsRequest\x12(\n" +
	"\x06states\x18\x01 \x03(\x0e2\x10.hearth.v1.StateR\x06states\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\tR\x05kinds\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"6\n" +
	"\x10ListJobsResponse\x12\"\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0e.hearth.v1.JobR\x04jobs\"\"\n" +
	"\x10CancelJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11CancelJobResponse\"!\n" +
	"\x0fWatchJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x15RegisterWorkerRequest\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x15.hearth.v1.WorkerInfoR\x04info\"b\n" +
	"\x16RegisterWorkerResponse\x12H\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"\xba\x01\n" +
	"\x0fLeaseJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05kinds\x18\x02 \x03(\tR\x05kinds\x12<\n" +
	"\fpoll_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vpollTimeout\x126\n" +
	"\tlease_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bleaseTtl\"4\n" +
	"\x10LeaseJobResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.hearth.v1.JobR\x03job\"w\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12/\n" +
	"\bprogress\x18\x03 \x01(\v2\x13.hearth.v1.ProgressR\bprogress\"f\n" +
	"\x11HeartbeatResponse\x129\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06cancel\x18\x02 \x01(\bR\x06cancel\"s\n" +
	"\x12CompleteJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12)\n" +
	"\x06result\x18\x03 \x01(\v2\x11.hearth.v1.ResultR\x06result\"\x15\n" +
	"\x13CompleteJobResponse\"i\n" +
	"\x0eFailJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"l\n" +
	"\x0fFailJobResponse\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x01 \x01(\bR\twillRetry\x12:\n" +
	"\vnext_run_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\"g\n" +
	"\x0ePutBlobRequest\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x18.hearth.v1.PutBlobHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"#\n" +
	"\rPutBlobHeader\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"7\n" +
	"\x0fPutBlobResponse\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.hearth.v1.BlobRefR\x03ref\"6\n" +
	"\x0eGetBlobRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.hearth.v1.BlobRefR\x03ref\"'\n" +
	"\x0fGetBlobResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"6\n" +
	"\x0eHasBlobRequest\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.hearth.v1.BlobRefR\x03ref\"+\n" +
	"\x0fHasBlobResponse\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\"\x12\n" +
	"\x10ListNodesRequest\"@\n" +
	"\x11ListNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.hearth.v1.WorkerInfoR\x05nodes*~\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATE_QUEUED\x10\x01\x12\x10\n" +
	"\fSTATE_LEASED\x10\x02\x12\x13\n" +
	"\x0fSTATE_SUCCEEDED\x10\x03\x12\x10\n" +
	"\fSTATE_FAILED\x10\x04\x12\x13\n" +
	"\x0fSTATE_CANCELLED\x10\x052\xd6\a\n" +
	"\vCoordinator\x12F\n" +
	"\tSubmitJob\x12\x1b.hearth.v1.SubmitJobRequest\x1a\x1c.hearth.v1.SubmitJobResponse\x122\n" +
	"\x06GetJob\x12\x18.hearth.v1.GetJobRequest\x1a\x0e.hearth.v1.Job\x12C\n" +
	"\bListJobs\x12\x1a.hearth.v1.ListJobsRequest\x1a\x1b.hearth.v1.ListJobsResponse\x12F\n" +
	"\tCancelJob\x12\x1b.hearth.v1.CancelJobRequest\x1a\x1c.hearth.v1.CancelJobResponse\x128\n" +
	"\bWatchJob\x12\x1a.hearth.v1.WatchJobRequest\x1a\x0e.hearth.v1.Job0\x01\x12U\n" +
	"\x0eRegisterWorker\x12 .hearth.v1.RegisterWorkerRequest\x1a!.hearth.v1.RegisterWorkerResponse\x12C\n" +
	"\bLeaseJob\x12\x1a.hearth.v1.LeaseJobRequest\x1a\x1b.hearth.v1.LeaseJobResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.hearth.v1.HeartbeatRequest\x1a\x1c.hearth.v1.HeartbeatResponse\x12L\n" +
	"\vCompleteJob\x12\x1d.hearth.v1.CompleteJobRequest\x1a\x1e.hearth.v1.CompleteJobResponse\x12@\n" +
	"\aFailJob\x12\x19.hearth.v1.FailJobRequest\x1a\x1a.hearth.v1.FailJobResponse\x12B\n" +
	"\aPutBlob\x12\x19.hearth.v1.PutBlobRequest\x1a\x1a.hearth.v1.PutBlobResponse(\x01\x12B\n" +
	"\aGetBlob\x12\x19.hearth.v1.GetBlobRequest\x1a\x1a.hearth.v1.GetBlobResponse0\x01\x12@\n" +
	"\aHasBlob\x12\x19.hearth.v1.HasBlobRequest\x1a\x1a.hearth.v1.HasBlobResponse\x12F\n" +
	"\tListNodes\x12\x1b.hearth.v1.ListNodesRequest\x1a\x1c.hearth.v1.ListNodesResponseB7Z5github.com/notpop/hearth/pkg/proto/hearth/v1;hearthv1b\x06proto3"

var (
	file_hearth_v1_hearth_proto_rawDescOnce sync.Once
	file_hearth_v1_hearth_proto_rawDescData []byte
)

func file_hearth_v1_hearth_proto_rawDescGZIP() []byte {
	file_hearth_v1_hearth_proto_rawDescOnce.Do(func() {
		file_hearth_v1_hearth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hearth_v1_hearth_proto_rawDesc), len(file_hearth_v1_hearth_proto_rawDesc)))
	})
	return file_hearth_v1_hearth_proto_rawDescData
}

var file_hearth_v1_hearth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hearth_v1_hearth_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_hearth_v1_hearth_proto_goTypes = []any{
	(State)(0),                     // 0: hearth.v1.State
	(*BlobRef)(nil),                // 1: hearth.v1.BlobRef
	(*BackoffPolicy)(nil),          // 2: hearth.v1.BackoffPolicy
	(*Spec)(nil),                   // 3: hearth.v1.Spec
	(*Lease)(nil),                  // 4: hearth.v1.Lease
	(*Result)(nil),                 // 5: hearth.v1.Result
	(*Progress)(nil),               // 6: hearth.v1.Progress
	(*Job)(nil),                    // 7: hearth.v1.Job
	(*WorkerInfo)(nil),             // 8: hearth.v1.WorkerInfo
	(*SubmitJobRequest)(nil),       // 9: hearth.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),      // 10: hearth.v1.SubmitJobResponse
	(*GetJobRequest)(nil),          // 11: hearth.v1.GetJobRequest
	(*ListJobsRequest)(nil),        // 12: hearth.v1.ListJobsRequest
	(*ListJobsResponse)(nil),       // 13: hearth.v1.ListJobsResponse
	(*CancelJobRequest)(nil),       // 14: hearth.v1.CancelJobRequest
	(*CancelJobResponse)(nil),      // 15: hearth.v1.CancelJobResponse
	(*WatchJobRequest)(nil),        // 16: hearth.v1.WatchJobRequest
	(*RegisterWorkerRequest)(nil),  // 17: hearth.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 18: hearth.v1.RegisterWorkerResponse
	(*LeaseJobRequest)(nil),        // 19: hearth.v1.LeaseJobRequest
	(*LeaseJobResponse)(nil),       // 20: hearth.v1.LeaseJobResponse
	(*HeartbeatRequest)(nil),       // 21: hearth.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 22: hearth.v1.HeartbeatResponse
	(*CompleteJobRequest)(nil),     // 23: hearth.v1.CompleteJobRequest
	(*CompleteJobResponse)(nil),    // 24: hearth.v1.CompleteJobResponse
	(*FailJobRequest)(nil),         // 25: hearth.v1.FailJobRequest
	(*FailJobResponse)(nil),        // 26: hearth.v1.FailJobResponse
	(*PutBlobRequest)(nil),         // 27: hearth.v1.PutBlobRequest
	(*PutBlobHeader)(nil),          // 28: hearth.v1.PutBlobHeader
	(*PutBlobResponse)(nil),        // 29: hearth.v1.PutBlobResponse
	(*GetBlobRequest)(nil),         // 30: hearth.v1.GetBlobRequest
	(*GetBlobResponse)(nil),        // 31: hearth.v1.GetBlobResponse
	(*HasBlobRequest)(nil),         // 32: hearth.v1.HasBlobRequest
	(*HasBlobResponse)(nil),        // 33: hearth.v1.HasBlobResponse
	(*ListNodesRequest)(nil),       // 34: hearth.v1.ListNodesRequest
	(*ListNodesResponse)(nil),      // 35: hearth.v1.ListNodesResponse
	(*durationpb.Duration)(nil),    // 36: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),  // 37: google.protobuf.Timestamp
}
var file_hearth_v1_hearth_proto_depIdxs = []int32{
	36, // 0: hearth.v1.BackoffPolicy.initial:type_name -> google.protobuf.Duration
	36, // 1: hearth.v1.BackoffPolicy.max:type_name -> google.protobuf.Duration
	1,  // 2: hearth.v1.Spec.blobs:type_name -> hearth.v1.BlobRef
	36, // 3: hearth.v1.Spec.lease_ttl:type_name -> google.protobuf.Duration
	2,  // 4: hearth.v1.Spec.backoff:type_name -> hearth.v1.BackoffPolicy
	37, // 5: hearth.v1.Lease.leased_at:type_name -> google.protobuf.Timestamp
	37, // 6: hearth.v1.Lease.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 7: hearth.v1.Result.blobs:type_name -> hearth.v1.BlobRef
	37, // 8: hearth.v1.Progress.reported_at:type_name -> google.protobuf.Timestamp
	3,  // 9: hearth.v1.Job.spec:type_name -> hearth.v1.Spec
	0,  // 10: hearth.v1.Job.state:type_name -> hearth.v1.State
	4,  // 11: hearth.v1.Job.lease:type_name -> hearth.v1.Lease
	5,  // 12: hearth.v1.Job.result:type_name -> hearth.v1.Result
	37, // 13: hearth.v1.Job.next_run_at:type_name -> google.protobuf.Timestamp
	37, // 14: hearth.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	37, // 15: hearth.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 16: hearth.v1.Job.progress:type_name -> hearth.v1.Progress
	37, // 17: hearth.v1.WorkerInfo.joined_at:type_name -> google.protobuf.Timestamp
	37, // 18: hearth.v1.WorkerInfo.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 19: hearth.v1.SubmitJobRequest.spec:type_name -> hearth.v1.Spec
	0,  // 20: hearth.v1.ListJobsRequest.states:type_name -> hearth.v1.State
	7,  // 21: hearth.v1.ListJobsResponse.jobs:type_name -> hearth.v1.Job
	8,  // 22: hearth.v1.RegisterWorkerRequest.info:type_name -> hearth.v1.WorkerInfo
	36, // 23: hearth.v1.RegisterWorkerResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	36, // 24: hearth.v1.LeaseJobRequest.poll_timeout:type_name -> google.protobuf.Duration
	36, // 25: hearth.v1.LeaseJobRequest.lease_ttl:type_name -> google.protobuf.Duration
	7,  // 26: hearth.v1.LeaseJobResponse.job:type_name -> hearth.v1.Job
	6,  // 27: hearth.v1.HeartbeatRequest.progress:type_name -> hearth.v1.Progress
	37, // 28: hearth.v1.HeartbeatResponse.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 29: hearth.v1.CompleteJobRequest.result:type_name -> hearth.v1.Result
	37, // 30: hearth.v1.FailJobResponse.next_run_at:type_name -> google.protobuf.Timestamp
	28, // 31: hearth.v1.PutBlobRequest.header:type_name -> hearth.v1.PutBlobHeader
	1,  // 32: hearth.v1.PutBlobResponse.ref:type_name -> hearth.v1.BlobRef
	1,  // 33: hearth.v1.GetBlobRequest.ref:type_name -> hearth.v1.BlobRef
	1,  // 34: hearth.v1.HasBlobRequest.ref:type_name -> hearth.v1.BlobRef
	8,  // 35: hearth.v1.ListNodesResponse.nodes:type_name -> hearth.v1.WorkerInfo
	9,  // 36: hearth.v1.Coordinator.SubmitJob:input_type -> hearth.v1.SubmitJobRequest
	11, // 37: hearth.v1.Coordinator.GetJob:input_type -> hearth.v1.GetJobRequest
	12, // 38: hearth.v1.Coordinator.ListJobs:input_type -> hearth.v1.ListJobsRequest
	14, // 39: hearth.v1.Coordinator.CancelJob:input_type -> hearth.v1.CancelJobRequest
	16, // 40: hearth.v1.Coordinator.WatchJob:input_type -> hearth.v1.WatchJobRequest
	17, // 41: hearth.v1.Coordinator.RegisterWorker:input_type -> hearth.v1.RegisterWorkerRequest
	19, // 42: hearth.v1.Coordinator.LeaseJob:input_type -> hearth.v1.LeaseJobRequest
	21, // 43: hearth.v1.Coordinator.Heartbeat:input_type -> hearth.v1.HeartbeatRequest
	23, // 44: hearth.v1.Coordinator.CompleteJob:input_type -> hearth.v1.CompleteJobRequest
	25, // 45: hearth.v1.Coordinator.FailJob:input_type -> hearth.v1.FailJobRequest
	27, // 46: hearth.v1.Coordinator.PutBlob:input_type -> hearth.v1.PutBlobRequest
	30, // 47: hearth.v1.Coordinator.GetBlob:input_type -> hearth.v1.GetBlobRequest
	32, // 48: hearth.v1.Coordinator.HasBlob:input_type -> hearth.v1.HasBlobRequest
	34, // 49: hearth.v1.Coordinator.ListNodes:input_type -> hearth.v1.ListNodesRequest
	10, // 50: hearth.v1.Coordinator.SubmitJob:output_type -> hearth.v1.SubmitJobResponse
	7,  // 51: hearth.v1.Coordinator.GetJob:output_type -> hearth.v1.Job
	13, // 52: hearth.v1.Coordinator.ListJobs:output_type -> hearth.v1.ListJobsResponse
	15, // 53: hearth.v1.Coordinator.CancelJob:output_type -> hearth.v1.CancelJobResponse
	7,  // 54: hearth.v1.Coordinator.WatchJob:output_type -> hearth.v1.Job
	18, // 55: hearth.v1.Coordinator.RegisterWorker:output_type -> hearth.v1.RegisterWorkerResponse
	20, // 56: hearth.v1.Coordinator.LeaseJob:output_type -> hearth.v1.LeaseJobResponse
	22, // 57: hearth.v1.Coordinator.Heartbeat:output_type -> hearth.v1.HeartbeatResponse
	24, // 58: hearth.v1.Coordinator.CompleteJob:output_type -> hearth.v1.CompleteJobResponse
	26, // 59: hearth.v1.Coordinator.FailJob:output_type -> hearth.v1.FailJobResponse
	29, // 60: hearth.v1.Coordinator.PutBlob:output_type -> hearth.v1.PutBlobResponse
	31, // 61: hearth.v1.Coordinator.GetBlob:output_type -> hearth.v1.GetBlobResponse
	33, // 62: hearth.v1.Coordinator.HasBlob:output_type -> hearth.v1.HasBlobResponse
	35, // 63: hearth.v1.Coordinator.ListNodes:output_type -> hearth.v1.ListNodesResponse
	50, // [50:64] is the sub-list for method output_type
	36, // [36:50] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_hearth_v1_hearth_proto_init() }
func file_hearth_v1_hearth_proto_init() {
	if File_hearth_v1_hearth_proto != nil {
		return
	}
	file_hearth_v1_hearth_proto_msgTypes[26].OneofWrappers = []any{
		(*PutBlobRequest_Header)(nil),
		(*PutBlobRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hearth_v1_hearth_proto_rawDesc), len(file_hearth_v1_hearth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hearth_v1_hearth_proto_goTypes,
		DependencyIndexes: file_hearth_v1_hearth_proto_depIdxs,
		EnumInfos:         file_hearth_v1_hearth_proto_enumTypes,
		MessageInfos:      file_hearth_v1_hearth_proto_msgTypes,
	}.Build()
	File_hearth_v1_hearth_proto = out.File
	file_hearth_v1_hearth_proto_goTypes = nil
	file_hearth_v1_hearth_proto_depIdxs = nil
}
